u = User.new(
  name: 'Mitch P',
  email: 'mpronschinske+sts@gmail.com', 
  password: ';phalanx', 
  password_confirmation: ';phalanx')
u.skip_confirmation!
u.save
u.update_column(:role, 'admin')

u = User.new(
  name: 'Member',
  email: 'member@example.com', 
  password: 'helloworld', 
  password_confirmation: 'helloworld')
u.skip_confirmation!
u.save

################

#Post and Tag Seeds


Post.create(url: "http://www.youtube.com/watch?v=75QC59i-dIY", user_id: 1, tag_list: "fantasy, adventure, orchestral, exploring")
Post.create(url: "http://www.youtube.com/watch?v=PWlLp5riuzk", user_id: 1, tag_list: "battle, epic")
Post.create(url: "http://www.youtube.com/watch?v=OWCB2DabJ04", user_id: 2, tag_list: "dramatic, epic")
Post.create(url: "http://www.youtube.com/watch?v=WzljtlGj_lA", user_id: 1, tag_list: "excitement")
Post.create(url: "http://www.youtube.com/watch?v=2cKXHVgH40Q", user_id: 1, tag_list: "happy, excitement")
Post.create(url: "http://www.youtube.com/watch?v=vLVyhWDnSOI", user_id: 1, tag_list: "inspirational")
Post.create(url: "http://www.youtube.com/watch?v=zpY3q8oMzJM", user_id: 1, tag_list: "piano, ambient, romance")
Post.create(url: "http://www.youtube.com/watch?v=oGx5P1N22pI", user_id: 1, tag_list: "tension")
Post.create(url: "http://www.youtube.com/watch?v=DT8S9rOd2zM", user_id: 1, tag_list: "sadness, bittersweet, love, romance")
Post.create(url: "http://www.youtube.com/watch?v=K5tsfpLm4F4", user_id: 1, tag_list: "bravery, confidence, battle, violin, driving")
Post.create(url: "http://www.youtube.com/watch?v=nNDFN2f07XQ", user_id: 1, tag_list: "orchestral, distortion, evil, dramatic, guitar")
Post.create(url: "http://www.youtube.com/watch?v=cqTVWJeixNI", user_id: 1, tag_list: "haunting, marimba")
Post.create(url: "http://www.youtube.com/watch?v=YdgF63xKTe0", user_id: 1, tag_list: "hope, possibilities, adventure, dramatic, piano, flying")
Post.create(url: "http://www.youtube.com/watch?v=eJ5IfryrCVs", user_id: 1, tag_list: "inspirational, sports, forging")
Post.create(url: "http://www.youtube.com/watch?v=lOPaw9B63hw", user_id: 1, tag_list: "driving, orchestral, dramatic, strings, melancholy, tension")
Post.create(url: "http://www.youtube.com/watch?v=M5LMP2NaZSg", user_id: 1, tag_list: "nostalgia, piano, love, bittersweet, ending, orchestral")
Post.create(url: "http://www.youtube.com/watch?v=7mxtY8ytEO0", user_id: 1, tag_list: "hope, melancholy, sadness, piano")
Post.create(url: "http://www.youtube.com/watch?v=dclghhnW4oU", user_id: 1, tag_list: "8-bit, adventure, confidence")
Post.create(url: "http://www.youtube.com/watch?v=b_ajArNJmjY", user_id: 1, tag_list: "confidence, angry, tension, distortion")
Post.create(url: "http://www.youtube.com/watch?v=hesg2_q-B-Q", user_id: 1, tag_list: "dramatic, building, preparing, sci-fi, hope")
Post.create(url: "http://www.youtube.com/watch?v=2PrK5sLskyw", user_id: 1, tag_list: "building, hope, bravery")
Post.create(url: "http://www.youtube.com/watch?v=NcaFf5RwrBY", user_id: 1, tag_list: "sci-fi, horn, evil, epic, angry")
Post.create(url: "http://www.youtube.com/watch?v=47MugvaePqA", user_id: 1, tag_list: "ambient, synth")
Post.create(url: "http://www.youtube.com/watch?v=NQUpYENOKyY", user_id: 1, tag_list: "ambient, synth")
Post.create(url: "http://www.youtube.com/watch?v=90b82L-FZVI", user_id: 1, tag_list: "ambient, synth")
Post.create(url: "http://www.youtube.com/watch?v=oMTmVGfnON0", user_id: 1, tag_list: "evil, synth")
Post.create(url: "http://www.youtube.com/watch?v=bmOTo_vbGD4", user_id: 1, tag_list: "medieval, village, accordion, happy, celebration")
Post.create(url: "http://www.youtube.com/watch?v=eFg4dyUuVlM", user_id: 1, tag_list: "happy, organ, celebration")
Post.create(url: "http://www.youtube.com/watch?v=WRdWLXiq9A8", user_id: 1, tag_list: "jazz, piano, comedic")
Post.create(url: "http://www.youtube.com/watch?v=E4ben9JspeA", user_id: 1, tag_list: "orchestral, comedic")
Post.create(url: "http://www.youtube.com/watch?v=u9a8HwoMEGY", user_id: 1, tag_list: "western, adventure, exploring")
Post.create(url: "http://www.youtube.com/watch?v=otO2hbfE2zM", user_id: 1, tag_list: "excitement, possibilities, adventure, flying, exploring, confidence")
Post.create(url: "http://www.youtube.com/watch?v=Lu_nvUBG0I4", user_id: 1, tag_list: "village, flute, adventure, exploring")
Post.create(url: "http://www.youtube.com/watch?v=Wp8RTgf4oK8", user_id: 1, tag_list: "exploring, hope, orchestral")
Post.create(url: "http://www.youtube.com/watch?v=ietzDT5lOpQ", user_id: 1, tag_list: "harp, exploring, haunting")
Post.create(url: "http://www.youtube.com/watch?v=6jAYLiM7QyE", user_id: 1, tag_list: "dramatic, bittersweet, ending, romance, love, inspirational")
Post.create(url: "http://www.youtube.com/watch?v=bjgOLnfbC0E", user_id: 1, tag_list: "orchestral, love, ending, romance, happy")
Post.create(url: "http://www.youtube.com/watch?v=odQrmRKD4xQ", user_id: 1, tag_list: "orchestral, possibilities, excitement, fantasy")
Post.create(url: "http://www.youtube.com/watch?v=5Ac3lcvdl1s", user_id: 1, tag_list: "bravery, confidence, adventure, dramatic, orchestral, fantasy")
Post.create(url: "http://www.youtube.com/watch?v=bGl4OM5X43I", user_id: 1, tag_list: "fantasy, possibilities, happy")
Post.create(url: "http://www.youtube.com/watch?v=pd5q7RLDTyw", user_id: 1, tag_list: "driving, bravery, hope, flying")
Post.create(url: "http://www.youtube.com/watch?v=1-EgMjgV-6c", user_id: 1, tag_list: "driving, violin, happy, flying")
Post.create(url: "http://www.youtube.com/watch?v=EjOatCkrT1M", user_id: 1, tag_list: "kabuki, battle, drums")
Post.create(url: "http://www.youtube.com/watch?v=osGV_1LxAgQ", user_id: 1, tag_list: "drums, kabuki, preparing, epic, tension")
Post.create(url: "http://www.youtube.com/watch?v=M2DbjbZz_dM", user_id: 1, tag_list: "kabuki, tension, battle")
Post.create(url: "http://www.youtube.com/watch?v=iUkpDAezStI", user_id: 1, tag_list: "medieval, epic, march, confidence")
Post.create(url: "http://www.youtube.com/watch?v=22yTf0kD6-g", user_id: 1, tag_list: "children's choir, hope, adventure, melancholy, medieval")
Post.create(url: "http://www.youtube.com/watch?v=1vU7XqToZso", user_id: 1, tag_list: "electric guitar, epic, preparing, confidence, sports")
Post.create(url: "http://www.youtube.com/watch?v=4E8wHTX5nac", user_id: 1, tag_list: "epic, preparing, battle, sports, confidence")
Post.create(url: "http://www.youtube.com/watch?v=U-ePLrPHWqg", user_id: 1, tag_list: "confidence, inspirational, epic, preparing, battle, sports")
Post.create(url: "http://www.youtube.com/watch?v=AnVRWD3qF2w", user_id: 1, tag_list: "relaxed, trip-hop, synth")
Post.create(url: "http://www.youtube.com/watch?v=UXLdczfvuBc", user_id: 1, tag_list: "synth, relaxed, latin")
Post.create(url: "http://www.youtube.com/watch?v=yU5jNz2rr6g", user_id: 1, tag_list: "relaxed, latin")
Post.create(url: "http://www.youtube.com/watch?v=4NwpLA0kLaQ", user_id: 1, tag_list: "ethereal, relaxed, romance, happy")
Post.create(url: "http://www.youtube.com/watch?v=W7UVfoXQT6w", user_id: 1, tag_list: "irish folk, excitement, relaxed")
Post.create(url: "http://www.youtube.com/watch?v=RHgYEsE8eEo", user_id: 1, tag_list: "haunting, relaxed")
Post.create(url: "http://www.youtube.com/watch?v=QGhUfhQ-_PI", user_id: 1, tag_list: "sci-fi, electric guitar, distortion, dramatic, hope, confidence")
Post.create(url: "http://www.youtube.com/watch?v=dEYvYGxt0gQ", user_id: 1, tag_list: "sci-fi, melancholy, hope, dramatic, haunting")
Post.create(url: "http://www.youtube.com/watch?v=K5R7Y_nZ6yw", user_id: 1, tag_list: "hope, possibilities, violin, lilting, space")
Post.create(url: "http://www.youtube.com/watch?v=NUmLZYDobMM", user_id: 1, tag_list: "epic, dramatic, horn, space")
Post.create(url: "http://www.youtube.com/watch?v=6QjPhe2RxGU", user_id: 1, tag_list: "driving, epic, evil, hope, space, confidence")
Post.create(url: "http://www.youtube.com/watch?v=lxhQZ0NsJlQ", user_id: 1, tag_list: "sports, angry, confidence, battle")
Post.create(url: "http://www.youtube.com/watch?v=XqWknWbIWCE", user_id: 1, tag_list: "sports, epic, bravery, battle, hope")
Post.create(url: "http://www.youtube.com/watch?v=M1BhZUUORqg", user_id: 1, tag_list: "western, tribal")
Post.create(url: "http://www.youtube.com/watch?v=W0IWB6qEn9o", user_id: 1, tag_list: "distortion, evil, tribal, battle")
Post.create(url: "http://www.youtube.com/watch?v=7GStKGNxU9U", user_id: 1, tag_list: "violin, victorian, dramatic, confidence")
Post.create(url: "http://www.youtube.com/watch?v=TGaJXHhp7Lw", user_id: 1, tag_list: "victorian, orchestral")
Post.create(url: "http://www.youtube.com/watch?v=4lsCTTYEXYg", user_id: 1, tag_list: "violin, village, hope, happy")
Post.create(url: "http://www.youtube.com/watch?v=WWWETTms5kg", user_id: 1, tag_list: "happy, village")
Post.create(url: "http://www.youtube.com/watch?v=nffKT1m8_Fk", user_id: 1, tag_list: "western, bravery")
Post.create(url: "http://www.youtube.com/watch?v=tg-yC0xcI9s", user_id: 1, tag_list: "western, battle, driving, drums")
Post.create(url: "http://www.youtube.com/watch?v=kimebj_pw78", user_id: 1, tag_list: "western, melancholy")
Post.create(url: "http://www.youtube.com/watch?v=NUJ7qjSvGgA", user_id: 1, tag_list: "8-bit")
Post.create(url: "http://www.youtube.com/watch?v=kUBHD2g9zq4", user_id: 1, tag_list: "8-bit, driving")
Post.create(url: "http://www.youtube.com/watch?v=N4SjivMja_o", user_id: 1, tag_list: "accordion, tension")
Post.create(url: "http://www.youtube.com/watch?v=poxDJHoYxCc", user_id: 1, tag_list: "relaxed, accordion, possibilities, fantasy")
Post.create(url: "http://www.youtube.com/watch?v=izJHIZZgEH8", user_id: 1, tag_list: "acoustic guitar, electric guitar, hope, happy")
Post.create(url: "http://www.youtube.com/watch?v=nsUhq8DC6Xc", user_id: 1, tag_list: "sci-fi, acoustic guitar, steady, chase, confidence")
Post.create(url: "http://www.youtube.com/watch?v=4kAtK3iQqHk", user_id: 1, tag_list: "brass, orchestral, epic, medieval, tension")
Post.create(url: "http://www.youtube.com/watch?v=f5hH-q3Xwig", user_id: 1, tag_list: "hope, anthem, epic, trumpet, brass, choir, confidence, bravery, orchestral, forging")
Post.create(url: "http://www.youtube.com/watch?v=nS3DIX0if8Y", user_id: 1, tag_list: "hope, anthem, epic, trumpet, brass, confidence, orchestra, electric guitar, possibilities, excitement")
Post.create(url: "http://www.youtube.com/watch?v=EatFk-4Ulgc", user_id: 1, tag_list: "epic, choir, battle, distortion")
Post.create(url: "http://www.youtube.com/watch?v=TpACwgiti80", user_id: 1, tag_list: "female vocalist, haunting, choir, epic, sadness")
Post.create(url: "http://www.youtube.com/watch?v=vmHbboM5yMA", user_id: 1, tag_list: "battle, epic, forging, choir, march")
Post.create(url: "http://www.youtube.com/watch?v=52Jlhl2mRW0", user_id: 1, tag_list: "orchestral, children's choir, bittersweet, romance, dramatic")
Post.create(url: "http://www.youtube.com/watch?v=p2lwFiIaMAE", user_id: 1, tag_list: "sadness, haunting, children's choir, evil")
Post.create(url: "http://www.youtube.com/watch?v=-DiQfy5BwvU", user_id: 1, tag_list: "epic, battle, confidence, drums")
Post.create(url: "http://www.youtube.com/watch?v=xntraDmha38", user_id: 1, tag_list: "driving, distortion, epic, confidence, bravery, battle")
Post.create(url: "http://www.youtube.com/watch?v=t0EKwWwCSKk", user_id: 1, tag_list: "distortion, ethereal, harp")
Post.create(url: "http://www.youtube.com/watch?v=5F_p3ZK1FGU", user_id: 1, tag_list: "epic, possibilities, bravery, drums, punchy")
Post.create(url: "http://www.youtube.com/watch?v=hbK4skSdpj0", user_id: 1, tag_list: "tension, dramatic, kabuki, drums, preparing, battle, epic")
Post.create(url: "http://www.youtube.com/watch?v=S8gmbWKXY_M", user_id: 1, tag_list: "hope, inspirational, bittersweet, orchestral, dramatic, drums")
Post.create(url: "http://www.youtube.com/watch?v=wsICJx8eHUg", user_id: 1, tag_list: "electric guitar, battle, epic, dramatic, female vocal, confidence, bravery")
Post.create(url: "http://www.youtube.com/watch?v=rIq9NgbdZJ0", user_id: 1, tag_list: "electric guitar, violin, evil, battle, dramatic")
Post.create(url: "http://www.youtube.com/watch?v=LRTiUqGEDI4", user_id: 1, tag_list: "piano, driving, female vocal, possibilities, latin")
Post.create(url: "http://www.youtube.com/watch?v=cCXY-499bBk", user_id: 1, tag_list: "brazilian, flute, mysterious, brass, latin")
Post.create(url: "http://www.youtube.com/watch?v=oKyfFpDrl0c", user_id: 1, tag_list: "flute, hope, inspirational, bittersweet, orchestral, dramatic")
Post.create(url: "http://www.youtube.com/watch?v=hDhPvrYY0kY", user_id: 1, tag_list: "evil, driving, forging")
Post.create(url: "http://www.youtube.com/watch?v=eOGkZsuFILU", user_id: 1, tag_list: "battle, forging, electric guitar, confidence")
Post.create(url: "http://www.youtube.com/watch?v=KVOOzlmrdjg", user_id: 1, tag_list: "harp, exploring, mysterious, happy")
Post.create(url: "http://www.youtube.com/watch?v=IzLZaNwDqns", user_id: 1, tag_list: "sci-fi, trumpet, horn, evil, epic, angry")
Post.create(url: "http://www.youtube.com/watch?v=fnooGOhLIdM", user_id: 1, tag_list: "dramatic, sadness, bravery, horn, strings")
Post.create(url: "http://www.youtube.com/watch?v=jkrgYFMJOq0", user_id: 1, tag_list: "excitement, violin, irish folk, western")
Post.create(url: "http://www.youtube.com/watch?v=bO24b9d8A4I", user_id: 1, tag_list: "celebration, happy, irish folk")
Post.create(url: "http://www.youtube.com/watch?v=ZrGLgx5IegY", user_id: 1, tag_list: "romance, trumpet, latin")
Post.create(url: "http://www.youtube.com/watch?v=Qga-Mwr_opM", user_id: 1, tag_list: "happy, latin")
Post.create(url: "http://www.youtube.com/watch?v=gdLVhuQTmRU", user_id: 1, tag_list: "female vocal, male vocal, haunting, melancholy")
Post.create(url: "http://www.youtube.com/watch?v=Td9V43f03Tw", user_id: 1, tag_list: "evil, choir, male vocal, battle")
Post.create(url: "http://www.youtube.com/watch?v=wIuUER_Rpe8", user_id: 1, tag_list: "female vocal, marimba, haunting, melancholy, sadness")
Post.create(url: "http://www.youtube.com/watch?v=emkLyq3EfLU", user_id: 1, tag_list: "violin, strings")
Post.create(url: "http://www.youtube.com/watch?v=ZWaLYBeLffk", user_id: 1, tag_list: "orchestral, confidence, excitement, strings, trumpet")
Post.create(url: "http://www.youtube.com/watch?v=u3X6YZ74aHA", user_id: 1, tag_list: "sci-fi, synth, epic, preparing, confidence, possibilities")
Post.create(url: "http://www.youtube.com/watch?v=_tasQjI9j6U", user_id: 1, tag_list: "sci-fi, synth, haunting, confidence")
Post.create(url: "http://www.youtube.com/watch?v=eMcBR0J1c4E", user_id: 1, tag_list: "epic, battle, preparing, march, brass, bravery, confidence")
Post.create(url: "http://www.youtube.com/watch?v=gZJZE_13Chc", user_id: 1, tag_list: "march, anthem, trumpet, bravery, confidence")
Post.create(url: "http://www.youtube.com/watch?v=4UfBqCw1Tl8", user_id: 1, tag_list: "bravery, epic, choir, trumpet, brass, orchestral")
Post.create(url: "http://www.youtube.com/watch?v=_skOHTKttHs", user_id: 1, tag_list: "violin, sadness")
Post.create(url: "http://www.youtube.com/watch?v=x8_gS7tI3eE", user_id: 1, tag_list: "violin, happy")
Post.create(url: "http://www.youtube.com/watch?v=n3zm2v6cnvo", user_id: 1, tag_list: "bravery, dramatic, inspirational, anthem")
Post.create(url: "http://www.youtube.com/watch?v=v58Sir62ML0", user_id: 1, tag_list: "anthem, confidence, brass, electric guitar, choir, epic")
Post.create(url: "http://www.youtube.com/watch?v=45Hv4eht4G0", user_id: 1, tag_list: "driving, dramatic, confidence")
Post.create(url: "http://www.youtube.com/watch?v=4LKIsWOSHAY", user_id: 1, tag_list: "female vocal, bravery, driving, melancholy, strings, drums")
Post.create(url: "http://www.youtube.com/watch?v=pgFKc2-OMV8", user_id: 1, tag_list: "galloping, dramatic, bravery")
Post.create(url: "http://www.youtube.com/watch?v=LNZmzLzvJo8", user_id: 1, tag_list: "bravery, female vocal, galloping")
Post.create(url: "http://www.youtube.com/watch?v=tBShZHLbC6c", user_id: 1, tag_list: "galloping, bravery, confidence, orchestral, punchy, battle, epic")
Post.create(url: "http://www.youtube.com/watch?v=8YgvzKjR798", user_id: 1, tag_list: "orchestral, nostalgia, lilting, relaxed")
Post.create(url: "http://www.youtube.com/watch?v=puRsvgjqySU", user_id: 1, tag_list: "orchestral, adventure, inspirational, march, hope")
Post.create(url: "http://www.youtube.com/watch?v=QSeArGEBMCA", user_id: 1, tag_list: "march, strings, inspirational, adventure")
Post.create(url: "http://www.youtube.com/watch?v=4-_XANMleDc", user_id: 1, tag_list: "hope, orchestral, battle, confidence, offbeat, inspirational")
Post.create(url: "http://www.youtube.com/watch?v=CdFkZZc9Uaw", user_id: 1, tag_list: "bittersweet, distortion, offbeat, latin")
Post.create(url: "http://www.youtube.com/watch?v=dWE0nlhpdq8", user_id: 1, tag_list: "battle, synth, offbeat, tension")
Post.create(url: "http://www.youtube.com/watch?v=zMHaHhdORjQ", user_id: 1, tag_list: "punchy, confidence, battle")
Post.create(url: "http://www.youtube.com/watch?v=R0-Ah_hwfVs", user_id: 1, tag_list: "piano, punchy, relaxed, happy")
Post.create(url: "http://www.youtube.com/watch?v=B9w-IRgkN70", user_id: 1, tag_list: "offbeat, building, strings, excitement")
Post.create(url: "http://www.youtube.com/watch?v=EPl9evfmD1A", user_id: 1, tag_list: "electric guitar, strings, tension, battle")
Post.create(url: "http://www.youtube.com/watch?v=Vf-m2o97gdI", user_id: 1, tag_list: "driving, strings, bravery, dramatic, hope, sadness")
Post.create(url: "http://www.youtube.com/watch?v=pDmEX3ToT78", user_id: 1, tag_list: "confidence, adventure, epic, choir, orchestral, nostalgia, excitement, possibilities, inspirational")
Post.create(url: "http://www.youtube.com/watch?v=9eZekO4RRUk", user_id: 1, tag_list: "galloping, choir, dramatic, battle, bravery, drums")


#############

# Playlist seeds

Tag.find_by_name("adventure").update_column("url", "96_s9eysPY4?list=PLn6gIVVWkLcS0e7QVeACpv9m7BPdgGqPs")
Tag.find_by_name("battle").update_column("url", "fx-f1yWWx_I?list=PLn6gIVVWkLcRbtiZH0rAOZD6iAEED5akc")
Tag.find_by_name("bittersweet").update_column("url", "6jAYLiM7QyE?list=PLn6gIVVWkLcRPyuSLr1gRI7TY6L15qUAt")
Tag.find_by_name("bravery").update_column("url", "K5tsfpLm4F4?list=PLn6gIVVWkLcTmppexCGD_BR_pskTC-D8i")
Tag.find_by_name("confidence").update_column("url", "ACsrDhqNg80?list=PLn6gIVVWkLcRwnvZ4WUcQpuX-3xtCrlCu")
Tag.find_by_name("dramatic").update_column("url", "_gBvQR-8W5I?list=PLn6gIVVWkLcQWPEitNTLnRGItDQ3gCXXh")
Tag.find_by_name("epic").update_column("url", "KzlAE3Z-vcA?list=PLn6gIVVWkLcRLLmGbTq1ZViCU9qsau9ba")
Tag.find_by_name("evil").update_column("url", "lmc21V-zBq0?list=PLn6gIVVWkLcQkXeSVg8xxMA5cwli3FW1h")
Tag.find_by_name("excitement").update_column("url", "Bg-RH9AfYVM?list=PLn6gIVVWkLcRSr5_dGOwy8lLXBLATq1Km")
Tag.find_by_name("happy").update_column("url", "rDyw-f5CXCk?list=PLn6gIVVWkLcT8dJKv9fMYynnCdlTjd1xN")
Tag.find_by_name("haunting").update_column("url", "oGx5P1N22pI?list=PLn6gIVVWkLcR6iFZE7u7hooM6C-M_fI8u")
Tag.find_by_name("hope").update_column("url", "BkE3ti_dPko?list=PLn6gIVVWkLcQw8OVPjCqTGRYmJd33UYGG")
Tag.find_by_name("inspirational").update_column("url", "puRsvgjqySU?list=PLn6gIVVWkLcRB4DQmie_x61ER15etU72m")
Tag.find_by_name("melancholy").update_column("url", "fjFuzr07mXE?list=PLn6gIVVWkLcQDqRgA9x1i6h5xOO8NiUhR")
Tag.find_by_name("nostalgia").update_column("url", "t_FmaQiQcNE?list=PLn6gIVVWkLcRvRfRIY5chD5QsWxoc3nKs")
Tag.find_by_name("possibilities").update_column("url", "c2T2knomWqQ?list=PLn6gIVVWkLcT2Do_xNRcwMEu-ZtB4bXuW")
Tag.find_by_name("sadness").update_column("url", "7mxtY8ytEO0?list=PLn6gIVVWkLcT6hcpCHlmE2G9kSpFQm7F4")
Tag.find_by_name("tension").update_column("url", "g8Pj6EoTGTc?list=PLn6gIVVWkLcTZiSrA9_htaguWI7WSFFVX")
Tag.find_by_name("mysterious").update_column("url", "f4YepC4W200?list=PLn6gIVVWkLcRLZ4v9H8oFgIrl6kIo2HGq")
Tag.find_by_name("romance").update_column("url", "DT8S9rOd2zM?list=PLn6gIVVWkLcRBCG3u7XTyLgjkBWtMgjbJ")
#.find_or_create_by_name   .update_attributes

