u = User.new(
  name: 'Mitch P',
  email: 'mpronschinske+sts@gmail.com', 
  password: ';phalanx', 
  password_confirmation: ';phalanx')
u.skip_confirmation!
u.save
u.update_column(:role, 'admin')

u = User.new(
  name: 'Member',
  email: 'member@example.com', 
  password: 'helloworld', 
  password_confirmation: 'helloworld')
u.skip_confirmation!
u.save

################

#Post and Tag Seeds

Post.create(url: "http://www.youtube.com/watch?v=75QC59i-dIY", user_id: 1, tag_list: "fantasy, adventure, orchestral, exploring")
Post.create(url: "http://www.youtube.com/watch?v=PWlLp5riuzk", user_id: 1, tag_list: "battle, epic")
Post.create(url: "http://www.youtube.com/watch?v=OWCB2DabJ04", user_id: 2, tag_list: "dramatic, epic")
Post.create(url: "http://www.youtube.com/watch?v=WzljtlGj_lA", user_id: 1, tag_list: "excitement")
Post.create(url: "http://www.youtube.com/watch?v=2cKXHVgH40Q", user_id: 1, tag_list: "happy, excitement")
Post.create(url: "http://www.youtube.com/watch?v=vLVyhWDnSOI", user_id: 1, tag_list: "inspirational")
Post.create(url: "http://www.youtube.com/watch?v=zpy3q8omzjm", user_id: 1, tag_list: "piano, ambient, romance")
Post.create(url: "http://www.youtube.com/watch?v=ogx5p1n22pi", user_id: 1, tag_list: "tension")
Post.create(url: "http://www.youtube.com/watch?v=dt8s9rod2zm", user_id: 1, tag_list: "sadness, bittersweet, love, romance")
Post.create(url: "http://www.youtube.com/watch?v=k5tsfplm4f4", user_id: 1, tag_list: "bravery, confidence, battle, violin, driving")
Post.create(url: "http://www.youtube.com/watch?v=nndfn2f07xq", user_id: 1, tag_list: "orchestral, distortion, evil, dramatic, guitar")
Post.create(url: "http://www.youtube.com/watch?v=cqtvwjeixni", user_id: 1, tag_list: "haunting, marimba")
Post.create(url: "http://www.youtube.com/watch?v=ydgf63xkte0", user_id: 1, tag_list: "hope, possibilities, adventure, dramatic, piano, flying")
Post.create(url: "http://www.youtube.com/watch?v=ej5ifryrcvs", user_id: 1, tag_list: "inspirational, sports, forging")
Post.create(url: "http://www.youtube.com/watch?v=lopaw9b63hw", user_id: 1, tag_list: "driving, orchestral, dramatic, strings, melancholy, tension")
Post.create(url: "http://www.youtube.com/watch?v=m5lmp2nazsg", user_id: 1, tag_list: "nostalgia, piano, love, bittersweet, ending, orchestral")
Post.create(url: "http://www.youtube.com/watch?v=7mxty8yteo0", user_id: 1, tag_list: "hope, melancholy, sadness, piano")
Post.create(url: "http://www.youtube.com/watch?v=dclghhnw4ou", user_id: 1, tag_list: "8-bit, adventure, confidence")
Post.create(url: "http://www.youtube.com/watch?v=b_ajarnjmjy", user_id: 1, tag_list: "confidence, angry, tension, distortion")
Post.create(url: "http://www.youtube.com/watch?v=hesg2_q-b-q", user_id: 1, tag_list: "dramatic, building, preparing, sci-fi, hope")
Post.create(url: "http://www.youtube.com/watch?v=2prk5slskyw", user_id: 1, tag_list: "building, hope, bravery")
Post.create(url: "http://www.youtube.com/watch?v=ncaff5rwrby", user_id: 1, tag_list: "sci-fi, horn, evil, epic, angry")
Post.create(url: "http://www.youtube.com/watch?v=47mugvaepqa", user_id: 1, tag_list: "ambient, synth")
Post.create(url: "http://www.youtube.com/watch?v=nqupyenokyy", user_id: 1, tag_list: "ambient, synth")
Post.create(url: "http://www.youtube.com/watch?v=90b82l-fzvi", user_id: 1, tag_list: "ambient, synth")
Post.create(url: "http://www.youtube.com/watch?v=omtmvgfnon0", user_id: 1, tag_list: "evil, synth")
Post.create(url: "http://www.youtube.com/watch?v=bmoto_vbgd4", user_id: 1, tag_list: "medieval, village, accordion, happy, celebration")
Post.create(url: "http://www.youtube.com/watch?v=efg4dyuuvlm", user_id: 1, tag_list: "happy, organ, celebration")
Post.create(url: "http://www.youtube.com/watch?v=wrdwlxiq9a8", user_id: 1, tag_list: "jazz, piano, comedic")
Post.create(url: "http://www.youtube.com/watch?v=e4ben9jspea", user_id: 1, tag_list: "orchestral, comedic")
Post.create(url: "http://www.youtube.com/watch?v=u9a8hwomegy", user_id: 1, tag_list: "western, adventure, exploring")
Post.create(url: "http://www.youtube.com/watch?v=oto2hbfe2zm", user_id: 1, tag_list: "excitement, possibilities, adventure, flying, exploring, confidence")
Post.create(url: "http://www.youtube.com/watch?v=lu_nvubg0i4", user_id: 1, tag_list: "village, flute, adventure, exploring")
Post.create(url: "http://www.youtube.com/watch?v=wp8rtgf4ok8", user_id: 1, tag_list: "exploring, hope, orchestral")
Post.create(url: "http://www.youtube.com/watch?v=ietzdt5lopq", user_id: 1, tag_list: "harp, exploring, haunting")
Post.create(url: "http://www.youtube.com/watch?v=6jaylim7qye", user_id: 1, tag_list: "dramatic, bittersweet, ending, romance, love, inspirational")
Post.create(url: "http://www.youtube.com/watch?v=bjgolnfbc0e", user_id: 1, tag_list: "orchestral, love, ending, romance, happy")
Post.create(url: "http://www.youtube.com/watch?v=odqrmrkd4xq", user_id: 1, tag_list: "orchestral, possibilities, excitement, fantasy")
Post.create(url: "http://www.youtube.com/watch?v=5ac3lcvdl1s", user_id: 1, tag_list: "bravery, confidence, adventure, dramatic, orchestral, fantasy")
Post.create(url: "http://www.youtube.com/watch?v=bgl4om5x43i", user_id: 1, tag_list: "fantasy, possibilities, happy")
Post.create(url: "http://www.youtube.com/watch?v=pd5q7rldtyw", user_id: 1, tag_list: "driving, bravery, hope, flying")
Post.create(url: "http://www.youtube.com/watch?v=1-egmjgv-6c", user_id: 1, tag_list: "driving, violin, happy, flying")
Post.create(url: "http://www.youtube.com/watch?v=ejoatckrt1m", user_id: 1, tag_list: "kabuki, battle, drums")
Post.create(url: "http://www.youtube.com/watch?v=osgv_1lxagq", user_id: 1, tag_list: "drums, kabuki, preparing, epic, tension")
Post.create(url: "http://www.youtube.com/watch?v=m2dbjbzz_dm", user_id: 1, tag_list: "kabuki, tension, battle")
Post.create(url: "http://www.youtube.com/watch?v=iukpdaezsti", user_id: 1, tag_list: "medieval, epic, march, confidence")
Post.create(url: "http://www.youtube.com/watch?v=22ytf0kd6-g", user_id: 1, tag_list: "children's choir, hope, adventure, melancholy, medieval")
Post.create(url: "http://www.youtube.com/watch?v=1vu7xqtozso", user_id: 1, tag_list: "electric guitar, epic, preparing, confidence, sports")
Post.create(url: "http://www.youtube.com/watch?v=4e8whtx5nac", user_id: 1, tag_list: "epic, preparing, battle, sports, confidence")
Post.create(url: "http://www.youtube.com/watch?v=u-eplrphwqg", user_id: 1, tag_list: "confidence, inspirational, epic, preparing, battle, sports")
Post.create(url: "http://www.youtube.com/watch?v=anvrwd3qf2w", user_id: 1, tag_list: "relaxed, trip-hop, synth")
Post.create(url: "http://www.youtube.com/watch?v=uxldczfvubc", user_id: 1, tag_list: "synth, relaxed, latin")
Post.create(url: "http://www.youtube.com/watch?v=yu5jnz2rr6g", user_id: 1, tag_list: "relaxed, latin")
Post.create(url: "http://www.youtube.com/watch?v=4nwpla0klaq", user_id: 1, tag_list: "ethereal, relaxed, romance, happy")
Post.create(url: "http://www.youtube.com/watch?v=w7uvfoxqt6w", user_id: 1, tag_list: "irish folk, excitement, relaxed")
Post.create(url: "http://www.youtube.com/watch?v=rhgyese8eeo", user_id: 1, tag_list: "haunting, relaxed")
Post.create(url: "http://www.youtube.com/watch?v=qghufhq-_pi", user_id: 1, tag_list: "sci-fi, electric guitar, distortion, dramatic, hope, confidence")
Post.create(url: "http://www.youtube.com/watch?v=deyvygxt0gq", user_id: 1, tag_list: "sci-fi, melancholy, hope, dramatic, haunting")
Post.create(url: "http://www.youtube.com/watch?v=k5r7y_nz6yw", user_id: 1, tag_list: "hope, possibilities, violin, lilting, space")
Post.create(url: "http://www.youtube.com/watch?v=numlzydobmm", user_id: 1, tag_list: "epic, dramatic, horn, space")
Post.create(url: "http://www.youtube.com/watch?v=6qjphe2rxgu", user_id: 1, tag_list: "driving, epic, evil, hope, space, confidence")
Post.create(url: "http://www.youtube.com/watch?v=lxhqz0nsjlq", user_id: 1, tag_list: "sports, angry, confidence, battle")
Post.create(url: "http://www.youtube.com/watch?v=xqwknwbiwce", user_id: 1, tag_list: "sports, epic, bravery, battle, hope")
Post.create(url: "http://www.youtube.com/watch?v=m1bhzuuorqg", user_id: 1, tag_list: "western, tribal")
Post.create(url: "http://www.youtube.com/watch?v=w0iwb6qen9o", user_id: 1, tag_list: "distortion, evil, tribal, battle")
Post.create(url: "http://www.youtube.com/watch?v=7gstkgnxu9u", user_id: 1, tag_list: "violin, victorian, dramatic, confidence")
Post.create(url: "http://www.youtube.com/watch?v=tgajxhhp7lw", user_id: 1, tag_list: "victorian, orchestral")
Post.create(url: "http://www.youtube.com/watch?v=4lscttyexyg", user_id: 1, tag_list: "violin, village, hope, happy")
Post.create(url: "http://www.youtube.com/watch?v=wwwettms5kg", user_id: 1, tag_list: "happy, village")
Post.create(url: "http://www.youtube.com/watch?v=nffkt1m8_fk", user_id: 1, tag_list: "western, bravery")
Post.create(url: "http://www.youtube.com/watch?v=tg-yc0xci9s", user_id: 1, tag_list: "western, battle, driving, drums")
Post.create(url: "http://www.youtube.com/watch?v=kimebj_pw78", user_id: 1, tag_list: "western, melancholy")
Post.create(url: "http://www.youtube.com/watch?v=nuj7qjsvgga", user_id: 1, tag_list: "8-bit")
Post.create(url: "http://www.youtube.com/watch?v=kubhd2g9zq4", user_id: 1, tag_list: "8-bit, driving")
Post.create(url: "http://www.youtube.com/watch?v=n4sjivmja_o", user_id: 1, tag_list: "accordion, tension")
Post.create(url: "http://www.youtube.com/watch?v=poxdjhoyxcc", user_id: 1, tag_list: "relaxed, accordion, possibilities, fantasy")
Post.create(url: "http://www.youtube.com/watch?v=izjhizzgeh8", user_id: 1, tag_list: "acoustic guitar, electric guitar, hope, happy")
Post.create(url: "http://www.youtube.com/watch?v=nsuhq8dc6xc", user_id: 1, tag_list: "sci-fi, acoustic guitar, steady, chase, confidence")
Post.create(url: "http://www.youtube.com/watch?v=4katk3iqqhk", user_id: 1, tag_list: "brass, orchestral, epic, medieval, tension")
Post.create(url: "http://www.youtube.com/watch?v=f5hh-q3xwig", user_id: 1, tag_list: "hope, anthem, epic, trumpet, brass, choir, confidence, bravery, orchestral, forging")
Post.create(url: "http://www.youtube.com/watch?v=ns3dix0if8y", user_id: 1, tag_list: "hope, anthem, epic, trumpet, brass, confidence, orchestra, electric guitar, possibilities, excitement")
Post.create(url: "http://www.youtube.com/watch?v=eatfk-4ulgc", user_id: 1, tag_list: "epic, choir, battle, distortion")
Post.create(url: "http://www.youtube.com/watch?v=tpacwgiti80", user_id: 1, tag_list: "female vocalist, haunting, choir, epic, sadness")
Post.create(url: "http://www.youtube.com/watch?v=vmhbbom5yma", user_id: 1, tag_list: "battle, epic, forging, choir, march")
Post.create(url: "http://www.youtube.com/watch?v=52jlhl2mrw0", user_id: 1, tag_list: "orchestral, children's choir, bittersweet, romance, dramatic")
Post.create(url: "http://www.youtube.com/watch?v=p2lwfiiamae", user_id: 1, tag_list: "sadness, haunting, children's choir, evil")
Post.create(url: "http://www.youtube.com/watch?v=-diqfy5bwvu", user_id: 1, tag_list: "epic, battle, confidence, drums")
Post.create(url: "http://www.youtube.com/watch?v=xntradmha38", user_id: 1, tag_list: "driving, distortion, epic, confidence, bravery, battle")
Post.create(url: "http://www.youtube.com/watch?v=t0ekwwwcskk", user_id: 1, tag_list: "distortion, ethereal, harp")
Post.create(url: "http://www.youtube.com/watch?v=5f_p3zk1fgu", user_id: 1, tag_list: "epic, possibilities, bravery, drums, punchy")
Post.create(url: "http://www.youtube.com/watch?v=hbk4sksdpj0", user_id: 1, tag_list: "tension, dramatic, kabuki, drums, preparing, battle, epic")
Post.create(url: "http://www.youtube.com/watch?v=s8gmbwkxy_m", user_id: 1, tag_list: "hope, inspirational, bittersweet, orchestral, dramatic, drums")
Post.create(url: "http://www.youtube.com/watch?v=wsicjx8ehug", user_id: 1, tag_list: "electric guitar, battle, epic, dramatic, female vocal, confidence, bravery")
Post.create(url: "http://www.youtube.com/watch?v=riq9ngbdzj0", user_id: 1, tag_list: "electric guitar, violin, evil, battle, dramatic")
Post.create(url: "http://www.youtube.com/watch?v=lrtiuqgedi4", user_id: 1, tag_list: "piano, driving, female vocal, possibilities, latin")
Post.create(url: "http://www.youtube.com/watch?v=ccxy-499bbk", user_id: 1, tag_list: "brazilian, flute, mysterious, brass, latin")
Post.create(url: "http://www.youtube.com/watch?v=okyffpdrl0c", user_id: 1, tag_list: "flute, hope, inspirational, bittersweet, orchestral, dramatic")
Post.create(url: "http://www.youtube.com/watch?v=hdhpvryy0ky", user_id: 1, tag_list: "evil, driving, forging")
Post.create(url: "http://www.youtube.com/watch?v=eogkzsufilu", user_id: 1, tag_list: "battle, forging, electric guitar, confidence")
Post.create(url: "http://www.youtube.com/watch?v=kvoozlmrdjg", user_id: 1, tag_list: "harp, exploring, mysterious, happy")
Post.create(url: "http://www.youtube.com/watch?v=izlzanwdqns", user_id: 1, tag_list: "sci-fi, trumpet, horn, evil, epic, angry")
Post.create(url: "http://www.youtube.com/watch?v=fnoogohlidm", user_id: 1, tag_list: "dramatic, sadness, bravery, horn, strings")
Post.create(url: "http://www.youtube.com/watch?v=jkrgyfmjoq0", user_id: 1, tag_list: "excitement, violin, irish folk, western")
Post.create(url: "http://www.youtube.com/watch?v=bo24b9d8a4i", user_id: 1, tag_list: "celebration, happy, irish folk")
Post.create(url: "http://www.youtube.com/watch?v=zrglgx5iegy", user_id: 1, tag_list: "romance, trumpet, latin")
Post.create(url: "http://www.youtube.com/watch?v=qga-mwr_opm", user_id: 1, tag_list: "happy, latin")
Post.create(url: "http://www.youtube.com/watch?v=gdlvhuqtmru", user_id: 1, tag_list: "female vocal, male vocal, haunting, melancholy")
Post.create(url: "http://www.youtube.com/watch?v=td9v43f03tw", user_id: 1, tag_list: "evil, choir, male vocal, battle")
Post.create(url: "http://www.youtube.com/watch?v=wiuuer_rpe8", user_id: 1, tag_list: "female vocal, marimba, haunting, melancholy, sadness")
Post.create(url: "http://www.youtube.com/watch?v=emklyq3eflu", user_id: 1, tag_list: "violin, strings")
Post.create(url: "http://www.youtube.com/watch?v=zwalybelffk", user_id: 1, tag_list: "orchestral, confidence, excitement, strings, trumpet")
Post.create(url: "http://www.youtube.com/watch?v=u3x6yz74aha", user_id: 1, tag_list: "sci-fi, synth, epic, preparing, confidence, possibilities")
Post.create(url: "http://www.youtube.com/watch?v=_tasqji9j6u", user_id: 1, tag_list: "sci-fi, synth, haunting, confidence")
Post.create(url: "http://www.youtube.com/watch?v=emcbr0j1c4e", user_id: 1, tag_list: "epic, battle, preparing, march, brass, bravery, confidence")
Post.create(url: "http://www.youtube.com/watch?v=gzjze_13chc", user_id: 1, tag_list: "march, anthem, trumpet, bravery, confidence")
Post.create(url: "http://www.youtube.com/watch?v=4ufbqcw1tl8", user_id: 1, tag_list: "bravery, epic, choir, trumpet, brass, orchestral")
Post.create(url: "http://www.youtube.com/watch?v=_skohtktths", user_id: 1, tag_list: "violin, sadness")
Post.create(url: "http://www.youtube.com/watch?v=x8_gs7ti3ee", user_id: 1, tag_list: "violin, happy")
Post.create(url: "http://www.youtube.com/watch?v=n3zm2v6cnvo", user_id: 1, tag_list: "bravery, dramatic, inspirational, anthem")
Post.create(url: "http://www.youtube.com/watch?v=v58sir62ml0", user_id: 1, tag_list: "anthem, confidence, brass, electric guitar, choir, epic")
Post.create(url: "http://www.youtube.com/watch?v=45hv4eht4g0", user_id: 1, tag_list: "driving, dramatic, confidence")
Post.create(url: "http://www.youtube.com/watch?v=4lkiswoshay", user_id: 1, tag_list: "female vocal, bravery, driving, melancholy, strings, drums")
Post.create(url: "http://www.youtube.com/watch?v=pgfkc2-omv8", user_id: 1, tag_list: "galloping, dramatic, bravery")
Post.create(url: "http://www.youtube.com/watch?v=lnzmzlzvjo8", user_id: 1, tag_list: "bravery, female vocal, galloping")
Post.create(url: "http://www.youtube.com/watch?v=tbshzhlbc6c", user_id: 1, tag_list: "galloping, bravery, confidence, orchestral, punchy, battle, epic")
Post.create(url: "http://www.youtube.com/watch?v=8ygvzkjr798", user_id: 1, tag_list: "orchestral, nostalgia, lilting, relaxed")
Post.create(url: "http://www.youtube.com/watch?v=pursvgjqysu", user_id: 1, tag_list: "orchestral, adventure, inspirational, march, hope")
Post.create(url: "http://www.youtube.com/watch?v=qseargebmca", user_id: 1, tag_list: "march, strings, inspirational, adventure")
Post.create(url: "http://www.youtube.com/watch?v=4-_xanmledc", user_id: 1, tag_list: "hope, orchestral, battle, confidence, offbeat, inspirational")
Post.create(url: "http://www.youtube.com/watch?v=cdfkzzc9uaw", user_id: 1, tag_list: "bittersweet, distortion, offbeat, latin")
Post.create(url: "http://www.youtube.com/watch?v=dwe0nlhpdq8", user_id: 1, tag_list: "battle, synth, offbeat, tension")
Post.create(url: "http://www.youtube.com/watch?v=zmhahhdorjq", user_id: 1, tag_list: "punchy, confidence, battle")
Post.create(url: "http://www.youtube.com/watch?v=r0-ah_hwfvs", user_id: 1, tag_list: "piano, punchy, relaxed, happy")
Post.create(url: "http://www.youtube.com/watch?v=b9w-irgkn70", user_id: 1, tag_list: "offbeat, building, strings, excitement")
Post.create(url: "http://www.youtube.com/watch?v=epl9evfmd1a", user_id: 1, tag_list: "electric guitar, strings, tension, battle")
Post.create(url: "http://www.youtube.com/watch?v=vf-m2o97gdi", user_id: 1, tag_list: "driving, strings, bravery, dramatic, hope, sadness")
Post.create(url: "http://www.youtube.com/watch?v=pdmex3tot78", user_id: 1, tag_list: "confidence, adventure, epic, choir, orchestral, nostalgia, excitement, possibilities, inspirational")
Post.create(url: "http://www.youtube.com/watch?v=9ezeko4rruk", user_id: 1, tag_list: "galloping, choir, dramatic, battle, bravery, drums")

#############

# Playlist seeds

Tag.find_by_name("adventure").update_column("url", "96_s9eysPY4?list=PLn6gIVVWkLcS0e7QVeACpv9m7BPdgGqPs")
Tag.find_by_name("battle").update_column("url", "fx-f1yWWx_I?list=PLn6gIVVWkLcRbtiZH0rAOZD6iAEED5akc")
Tag.find_by_name("bittersweet").update_column("url", "6jAYLiM7QyE?list=PLn6gIVVWkLcRPyuSLr1gRI7TY6L15qUAt")
Tag.find_by_name("bravery").update_column("url", "K5tsfpLm4F4?list=PLn6gIVVWkLcTmppexCGD_BR_pskTC-D8i")
Tag.find_by_name("confidence").update_column("url", "ACsrDhqNg80?list=PLn6gIVVWkLcRwnvZ4WUcQpuX-3xtCrlCu")
Tag.find_by_name("dramatic").update_column("url", "_gBvQR-8W5I?list=PLn6gIVVWkLcQWPEitNTLnRGItDQ3gCXXh")
Tag.find_by_name("epic").update_column("url", "KzlAE3Z-vcA?list=PLn6gIVVWkLcRLLmGbTq1ZViCU9qsau9ba")
Tag.find_by_name("evil").update_column("url", "lmc21V-zBq0?list=PLn6gIVVWkLcQkXeSVg8xxMA5cwli3FW1h")
Tag.find_by_name("excitement").update_column("url", "Bg-RH9AfYVM?list=PLn6gIVVWkLcRSr5_dGOwy8lLXBLATq1Km")
Tag.find_by_name("happy").update_column("url", "rDyw-f5CXCk?list=PLn6gIVVWkLcT8dJKv9fMYynnCdlTjd1xN")
Tag.find_by_name("haunting").update_column("url", "oGx5P1N22pI?list=PLn6gIVVWkLcR6iFZE7u7hooM6C-M_fI8u")
Tag.find_by_name("hope").update_column("url", "BkE3ti_dPko?list=PLn6gIVVWkLcQw8OVPjCqTGRYmJd33UYGG")
Tag.find_by_name("inspirational").update_column("url", "puRsvgjqySU?list=PLn6gIVVWkLcRB4DQmie_x61ER15etU72m")
Tag.find_by_name("melancholy").update_column("url", "fjFuzr07mXE?list=PLn6gIVVWkLcQDqRgA9x1i6h5xOO8NiUhR")
Tag.find_by_name("nostalgia").update_column("url", "t_FmaQiQcNE?list=PLn6gIVVWkLcRvRfRIY5chD5QsWxoc3nKs")
Tag.find_by_name("possibilities").update_column("url", "c2T2knomWqQ?list=PLn6gIVVWkLcT2Do_xNRcwMEu-ZtB4bXuW")
Tag.find_by_name("sadness").update_column("url", "7mxtY8ytEO0?list=PLn6gIVVWkLcT6hcpCHlmE2G9kSpFQm7F4")
Tag.find_by_name("tension").update_column("url", "g8Pj6EoTGTc?list=PLn6gIVVWkLcTZiSrA9_htaguWI7WSFFVX")
Tag.find_by_name("mysterious").update_column("url", "f4YepC4W200&list=PLn6gIVVWkLcRLZ4v9H8oFgIrl6kIo2HGq")
Tag.find_by_name("romance").update_column("url", "DT8S9rOd2zM?list=PLn6gIVVWkLcRBCG3u7XTyLgjkBWtMgjbJ")
#.find_or_create_by_name   .update_attributes

